# Generated by Django 5.2.17 on 2026-10-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0002_documento_mensaje_error_documento_paginas_sin_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='biblioteca.coleccion')),
            ],
            options={
                'verbose_name': 'conversación',
                'verbose_name_plural': 'conversaciones',
                'ordering': ['-actualizada'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente')], max_length=10)),
                ('contenido', models.TextField()),
                ('citas', models.JSONField(blank=True, default=list)),
                ('sin_respuesta', models.BooleanField(default=False)),
                ('interrumpida', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversacion')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['creado', 'id'],
            },
        ),
    ]
