# Generated by Django 5.2.17 on 2026-10-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacion',
            options={'ordering': ['-actualizada', '-id'], 'verbose_name': 'conversación', 'verbose_name_plural': 'conversaciones'},
        ),
    ]
