# Generated by Django 5.2.17 on 2026-10-05 01:43

import biblioteca.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'colección',
                'verbose_name_plural': 'colecciones',
                'ordering': ['-actualizada'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=biblioteca.models.ruta_documento)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano_bytes', models.PositiveBigIntegerField()),
                ('num_paginas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='biblioteca.coleccion')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-subido'],
            },
        ),
        migrations.AddConstraint(
            model_name='coleccion',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('propietario'), name='coleccion_nombre_unico_por_usuario'),
        ),
    ]
