# Generated by Django 5.2.17 on 2026-10-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='mensaje_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='paginas_sin_texto',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
