# Generated by Django 5.2.17 on 2026-10-05 02:54

import django.db.models.deletion
import pgvector.django.indexes
from pgvector.django import VectorExtension
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0002_documento_mensaje_error_documento_paginas_sin_texto'),
    ]

    operations = [
        # CREATE EXTENSION vector: activa pgvector en esta base de datos
        VectorExtension(),
        migrations.CreateModel(
            name='Fragmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('modelo_embedding', models.CharField(max_length=80)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='biblioteca.documento')),
            ],
            options={
                'verbose_name': 'fragmento',
                'verbose_name_plural': 'fragmentos',
                'ordering': ['documento', 'orden'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='fragmento_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('documento', 'orden'), name='fragmento_orden_unico')],
            },
        ),
    ]
